### ISSUE TITLE
Cant find controller

### ISSUE THREAD

**Issue by runthis** [tigermendoza/DJ-Hero-Traktor-mapping#1]
pd-extended cannot find the usb device.  Here are the outputs I get.

hidin: << device closed
hidin: >> opening device: "USB Receiver"
hidin: >> device has 1 input elements
hidin: >> opening device: "Macally ICEKEY2 Keyboard"
hidin: >> device has 576 input elements
hidin: >> opening device: "Macally ICEKEY2 Keyboard"
hidin: >> device has 3 input elements
hidin: -- could not get device #4: Access is denied.

hidin: -- can not read from mouse and keyboard
hidin: >> opening device: "USB Receiver"
hidin: >> device has 1 input elements
hidin: -- could not get device #6: Access is denied.

hidin: -- can not read from mouse and keyboard
hidin: >> opening device: "USB Receiver"
hidin: >> device has 4 input elements

Not sure what needs to change here. Device is on, connected and recognized by the computer. I have quote a few USB devices plugged in

**Comment by tigermendoza** [comment]
Hmmm... Never had that before. It might be that you've got more USB devices than the multi select box get to. You could try replacing it with a fixed number though.

Not that it should make much difference but what OS are you using?

**Comment by runthis** [comment]
I saw your reply and forgot to reply back. I did get it working via inputting a different number. Looks like for me it was USB device number 17 :D 

Cheers

**Comment by tigermendoza** [comment]
Excellent! Have fun!
